--
-- 用于 https://github.com/supabase/supabase/tree/master/examples/slack-clone/nextjs-slack-clone
--

-- 自定义类型
create type public.app_permission as enum ('channels.delete', 'messages.delete');
create type public.app_role as enum ('admin', 'moderator');
create type public.user_status as enum ('ONLINE', 'OFFLINE');

-- 用户表
create table public.users (
  id          uuid references auth.users not null primary key, -- 来自 auth.users 的 UUID
  username    text,
  status      user_status default 'OFFLINE'::public.user_status
);
comment on table public.users is '每个用户的个人资料数据。';
comment on column public.users.id is '引用内部 Supabase Auth 用户。';

-- 频道表
create table public.channels (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  slug          text not null unique,
  created_by    uuid references public.users not null
);
comment on table public.channels is '主题和群组。';

-- 消息表
create table public.messages (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  message       text,
  user_id       uuid references public.users not null,
  channel_id    bigint references public.channels on delete cascade not null
);
comment on table public.messages is '每个用户发送的单条消息。';

-- 用户角色表
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references public.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is '每个用户的应用角色。';

-- 角色权限表
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is '每个角色的应用权限。';

-- 基于角色的访问控制授权（RBAC）
create function public.authorize(
  requested_permission app_permission
)
returns boolean as $$
declare
  bind_permissions int;
begin
  select count(*)
  from public.role_permissions
  where role_permissions.permission = authorize.requested_permission
    and role_permissions.role = (auth.jwt() ->> 'user_role')::public.app_role
  into bind_permissions;
  
  return bind_permissions > 0;
end;
$$ language plpgsql security definer set search_path = public;

-- 保护数据表安全
alter table public.users enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;
create policy "允许已登录用户读取" on public.users for select using ( auth.role() = 'authenticated' );
create policy "允许个人插入" on public.users for insert with check ( auth.uid() = id );
create policy "允许个人更新" on public.users for update using ( auth.uid() = id );
create policy "允许已登录用户读取" on public.channels for select using ( auth.role() = 'authenticated' );
create policy "允许个人插入" on public.channels for insert with check ( auth.uid() = created_by );
create policy "允许个人删除" on public.channels for delete using ( auth.uid() = created_by );
create policy "允许授权删除" on public.channels for delete using ( authorize('channels.delete') );
create policy "允许已登录用户读取" on public.messages for select using ( auth.role() = 'authenticated' );
create policy "允许个人插入" on public.messages for insert with check ( auth.uid() = user_id );
create policy "允许个人更新" on public.messages for update using ( auth.uid() = user_id );
create policy "允许个人删除" on public.messages for delete using ( auth.uid() = user_id );
create policy "允许授权删除" on public.messages for delete using ( authorize('messages.delete') );
create policy "允许个人读取" on public.user_roles for select using ( auth.uid() = user_id );

-- 变更时发送"先前数据"
alter table public.users replica identity full; 
alter table public.channels replica identity full; 
alter table public.messages replica identity full;

-- 向 public.users 插入一行并分配角色
create function public.handle_new_user() 
returns trigger as $$
declare is_admin boolean;
begin
  insert into public.users (id, username)
  values (new.id, new.email);
  
  select count(*) = 1 from auth.users into is_admin;
  
  if position('+supaadmin@' in new.email) > 0 then
    insert into public.user_roles (user_id, role) values (new.id, 'admin');
  elsif position('+supamod@' in new.email) > 0 then
    insert into public.user_roles (user_id, role) values (new.id, 'moderator');
  end if;
  
  return new;
end;
$$ language plpgsql security definer set search_path = auth, public;

-- 每次创建用户时触发该函数
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

/**
 * 实时订阅
 * 仅允许监听 public 模式下的表。
 */

begin; 
  -- 移除实时发布
  drop publication if exists supabase_realtime; 

  -- 重新创建发布，但不为任何表启用
  create publication supabase_realtime;  
commit;

-- 将表添加到发布
alter publication supabase_realtime add table public.channels;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.users;

/**
 * 辅助函数
 * 创建测试用户辅助方法。
 */
create or replace function public.create_user(
    email text
) returns uuid
    security definer
    set search_path = auth
as $$
  declare
  user_id uuid;
begin
  user_id := extensions.uuid_generate_v4();
  
  insert into auth.users (id, email)
    values (user_id, email)
    returning id into user_id;

    return user_id;
end;
$$ language plpgsql;