-- 创建文件哈希表来管理重复文件
CREATE TABLE IF NOT EXISTS public.file_hashes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hash_value TEXT NOT NULL UNIQUE,  -- 文件的哈希值
  file_path TEXT NOT NULL,          -- 文件在存储中的路径
  file_size BIGINT,                 -- 文件大小
  file_type TEXT,                   -- 文件类型
  reference_count INTEGER DEFAULT 1, -- 引用计数
  inserted_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- 为哈希值创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS file_hashes_hash_value_idx ON public.file_hashes (hash_value);

-- 向 messages 表添加 file_hash_id 字段，用于关联文件哈希
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS file_hash_id BIGINT REFERENCES public.file_hashes(id);

-- 更新行级安全策略
ALTER TABLE public.file_hashes ENABLE ROW LEVEL SECURITY;

-- 为 file_hashes 表创建策略
CREATE POLICY "Allow logged-in read access" ON public.file_hashes FOR SELECT USING ( auth.role() = 'authenticated' );
CREATE POLICY "Allow individual insert access" ON public.file_hashes FOR INSERT WITH CHECK ( auth.role() = 'authenticated' );
CREATE POLICY "Allow individual update access" ON public.file_hashes FOR UPDATE USING ( auth.role() = 'authenticated' );
CREATE POLICY "Allow individual delete access" ON public.file_hashes FOR DELETE USING ( auth.role() = 'authenticated' );

-- 为实时订阅添加表
ALTER TABLE public.file_hashes REPLICA IDENTITY FULL;

-- 添加到实时订阅发布
ALTER PUBLICATION supabase_realtime ADD TABLE public.file_hashes;