--
-- PPChat 完整数据库脚本
-- 按顺序执行：类型 -> 表 -> 函数 -> 触发器 -> RLS策略 -> 实时订阅
--

-- ============================================
-- 1. 自定义类型
-- ============================================

create type public.app_permission as enum ('channels.delete', 'messages.delete');
create type public.app_role as enum ('admin', 'moderator');
create type public.user_status as enum ('ONLINE', 'OFFLINE');

-- ============================================
-- 2. 数据表
-- ============================================

-- USERS 用户表
create table public.users (
  id          uuid references auth.users not null primary key,
  username    text unique,
  status      user_status default 'OFFLINE'::public.user_status
);
comment on table public.users is 'Profile data for each user.';
comment on column public.users.id is 'References the internal Supabase Auth user.';
comment on column public.users.username is 'Unique username for login.';

-- CHANNELS 频道表（含私密房间支持）
create table public.channels (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  slug          text not null unique,
  created_by    uuid references public.users not null,
  is_private    boolean default false not null,
  password      text
);
comment on table public.channels is 'Topics and groups.';
comment on column public.channels.is_private is 'Whether the channel is private (requires password to join)';
comment on column public.channels.password is 'Password for private channels';

-- MESSAGES 消息表
create table public.messages (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  message       text,
  user_id       uuid references public.users not null,
  channel_id    bigint references public.channels on delete cascade not null,
  message_type  text default 'text' not null
);
comment on table public.messages is 'Individual messages sent by each user.';
comment on column public.messages.message_type is 'Message type: text or image';

-- USER ROLES 用户角色表
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references public.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- ROLE PERMISSIONS 角色权限表
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

-- ============================================
-- 3. 函数
-- ============================================

-- RBAC授权函数
create function public.authorize(
  requested_permission app_permission
)
returns boolean as $$
declare
  bind_permissions int;
begin
  select count(*)
  from public.role_permissions
  where role_permissions.permission = authorize.requested_permission
    and role_permissions.role = (auth.jwt() ->> 'user_role')::public.app_role
  into bind_permissions;
  
  return bind_permissions > 0;
end;
$$ language plpgsql security definer set search_path = public;

-- 新用户处理函数
create function public.handle_new_user() 
returns trigger as $$
declare is_admin boolean;
begin
  insert into public.users (id, username)
  values (new.id, new.email);
  
  select count(*)= 1 from auth.users into is_admin;
  
  if position('+supaadmin@' in new.email) > 0 then
    insert into public.user_roles (user_id, role) values (new.id, 'admin');
  elsif position('+supamod@' in new.email) > 0 then
    insert into public.user_roles (user_id, role) values (new.id, 'moderator');
  end if;
  
  return new;
end;
$$ language plpgsql security definer set search_path = auth, public;

-- Auth Hook: JWT自定义声明
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
  declare
    claims jsonb;
    user_role public.app_role;
  begin
    select role into user_role from public.user_roles where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    if user_role is not null then
      claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    else 
      claims := jsonb_set(claims, '{user_role}', 'null');
    end if;

    event := jsonb_set(event, '{claims}', claims);

    return event;
  end;
$$;

-- 测试用户创建函数
create or replace function public.create_user(
    email text
) returns uuid
    security definer
    set search_path = auth
as $$
  declare
  user_id uuid;
begin
  user_id := extensions.uuid_generate_v4();
  
  insert into auth.users (id, email)
    values (user_id, email)
    returning id into user_id;

    return user_id;
end;
$$ language plpgsql;

-- 根据用户名查找邮箱（用于用户名登录）
create or replace function public.get_email_by_username(username_input text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  found_email text;
begin
  -- 先从public.users查找对应的用户id，再从auth.users获取邮箱
  select au.email into found_email
  from public.users pu
  join auth.users au on pu.id = au.id
  where lower(pu.username) = lower(username_input);
  
  return found_email;
end;
$$;

-- ============================================
-- 4. 触发器
-- ============================================

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================
-- 5. 行级安全策略 (RLS)
-- ============================================

alter table public.users enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

-- Users 策略
create policy "Allow logged-in read access" on public.users for select using ( auth.role() = 'authenticated' );
create policy "Allow individual insert access" on public.users for insert with check ( auth.uid() = id );
create policy "Allow individual update access" on public.users for update using ( auth.uid() = id );

-- Channels 策略
create policy "Allow logged-in read access" on public.channels for select using ( auth.role() = 'authenticated' );
create policy "Allow individual insert access" on public.channels for insert with check ( auth.uid() = created_by );
create policy "Allow individual delete access" on public.channels for delete using ( auth.uid() = created_by );
create policy "Allow authorized delete access" on public.channels for delete using ( authorize('channels.delete') );

-- Messages 策略
create policy "Allow logged-in read access" on public.messages for select using ( auth.role() = 'authenticated' );
create policy "Allow individual insert access" on public.messages for insert with check ( auth.uid() = user_id );
create policy "Allow individual update access" on public.messages for update using ( auth.uid() = user_id );
create policy "Allow individual delete access" on public.messages for delete using ( auth.uid() = user_id );
create policy "Allow authorized delete access" on public.messages for delete using ( authorize('messages.delete') );
-- 允许管理员删除任何消息
create policy "Allow admins to delete any message" on public.messages for delete
using (
  exists (
    select 1 from public.user_roles 
    where user_id = auth.uid() and role = 'admin'
  )
);

-- User Roles 策略（允许用户读取自己的角色）
create policy "Users read own role" on public.user_roles for select 
to authenticated
using ( user_id = auth.uid() );

-- 授权 authenticated 角色读取权限
grant select on public.user_roles to authenticated;

-- ============================================
-- 6. 副本标识（用于实时订阅）
-- ============================================

alter table public.users replica identity full; 
alter table public.channels replica identity full; 
alter table public.messages replica identity full;

-- ============================================
-- 7. 实时订阅发布
-- ============================================

begin; 
  drop publication if exists supabase_realtime; 
  create publication supabase_realtime;  
commit;

alter publication supabase_realtime add table public.channels;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.users;

-- ============================================
-- 8. Auth Hook 权限配置
-- ============================================

grant usage on schema public to supabase_auth_admin;

grant execute
  on function public.custom_access_token_hook
  to supabase_auth_admin;

revoke execute
  on function public.custom_access_token_hook
  from authenticated, anon, public;

grant all
  on table public.user_roles
to supabase_auth_admin;

revoke all
  on table public.user_roles
  from authenticated, anon, public;

create policy "Allow auth admin to read user roles" ON public.user_roles
as permissive for select
to supabase_auth_admin
using (true);

-- ============================================
-- 9. Storage 权限配置 (chat-images bucket)
-- ============================================

-- 注意：需要先在 Supabase Dashboard 中创建名为 'chat-images' 的 bucket
-- 并将其设置为 Public bucket
-- 图片存储路径结构: chat/{userId}/{timestamp}_{random}.jpg

-- 允许认证用户上传图片到 chat-images bucket
create policy "Allow authenticated users to upload images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'chat-images');

-- 允许认证用户更新自己上传的图片
-- 路径结构: chat/{userId}/file.jpg，所以取 foldername 的第二个元素
create policy "Allow users to update own images"
on storage.objects for update
to authenticated
using (bucket_id = 'chat-images' and auth.uid()::text = (storage.foldername(name))[2])
with check (bucket_id = 'chat-images' and auth.uid()::text = (storage.foldername(name))[2]);

-- 允许认证用户删除自己上传的图片
create policy "Allow users to delete own files"
on storage.objects for delete
to authenticated
using (bucket_id = 'chat-images' and auth.uid()::text = (storage.foldername(name))[2]);

-- 允许所有人公开读取和列出图片
create policy "Allow public read and list"
on storage.objects for select
to public
using (bucket_id = 'chat-images');
